matrix1 = np.random.randint(0, 10, (rows, cols))

Generate two random 3x3 matrices (matrix1 and matrix2) with values between 0 and 9.

In [ ]:
import numpy as np

# Define the size of the matrices
rows, cols = 3, 3

# Create two 2D arrays (matrices) of the same size with random integers
matrix1 = np.random.randint(0, 10, (rows, cols))
matrix2 = np.random.randint(0, 10, (rows, cols))

# Perform element-wise addition of the two matrices
result_matrix = np.add(matrix1, matrix2)

# Display the matrices and the result
print("Matrix 1:")
print(matrix1)
print("\nMatrix 2:")
print(matrix2)
print("\nResulting Matrix after Addition:")
print(result_matrix)


Matrix 1:
[[6 9 9]
 [4 2 5]
 [9 5 7]]

Matrix 2:
[[3 7 9]
 [2 1 9]
 [4 9 1]]

Resulting Matrix after Addition:
[[ 9 16 18]
 [ 6  3 14]
 [13 14  8]]
